name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
    
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 12.x
        
      - name: Install dependencies
        run: |
          cd backend
          yarn
          
      - name: Run Build
        run: |
          cd backend
          yarn build
      
      
      - name: copy dist to GCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_URL }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "dist"
          target: "test"

    # instalar depenencias
    # executar build
      
    # copiar pasta para GCP
    # executar yarn GPC
    # executar migrations
    # executar build   
    # restart PM2
