name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    env:
      key1: ${{ secrets.SSH_URL }}
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - run: echo $key1
      if: ${{env.key1}} == 22
#     steps:
#       - uses: actions/checkout@v2
      
#       - name: executing remote ssh commands using password
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.SSH_URL }}
#           username: ${{ secrets.SSH_USER }}
#           port: ${{ secrets.SSH_PORT }}
#           key: ${{ secrets.SSH_KEY }}
#           script: whoami

    # instalar depenencias
    # executar build
      
    # copiar pasta para GCP
    # executar yarn GPC
    # executar migrations
    # executar build   
    # restart PM2
